### PR TITLE
Settable font sizes with menu

### PR DESCRIPTION
**Pull request by vsonnier**
@cjcliffe Hello there. This is an attempt to help with issue #352, by adding ability to have different configurable font sizes, especially for 4K screens.
Note that I tested on a 1920x1080 screen.

Modifications:
-  Add a menu "Display" offering to tune the font size: Normal (1x) , Medium (1.5x), Large (2x) scale.
-  Font scale is applied on dynamic text (scope, floating labels, dBs...)

In addition, some graphical elements were made a little bigger, but are remained untouched by the zoom: (also because I didn't manage to find a way to do it properly !)  
-  Mode tiles get from 40pix to 44pix large, now displaying 18pix font instead of 16pix: quite clearer to the eye, and not wasting much more space,
-  TunerIndexedBar now displays a 32pix font instead of 24pix while fitting in the same space,
- All toggles 'V', 'S', 'M'...etc buttons are now 18pix instead 16pix, still fitting in the same space.

On the API side, GLFont::getFont no longer access fonts directly, but  GLFont::getFont(fontSize, scale) returns a Drawer proxy object that has computed the best font able to render fontSize*scale, with fontSize and scale that can be arbitrary.

So now fonts[] is only there to provide discrete Levels of Detail for the rendering and are actually independent of the scale chosen. The more fonts there are, the cleaner the rendering may be, by minimizing rescaling artifacts.
Also, because there are plenty of fonts now, they go to their own 'fonts' subdir.

The numerous commits only reflect the course of developemment, and only the squash of them make sense :)

### CODE REVIEW

**Comment by vsonnier** [comment]
@cjcliffe  Medium (1.5x) is not bad, but Large (2x) is....well you'll see :) 
Maybe still useful in case of video projecting with a poorly defined device, with  an audience far from the screen.

**Comment by cjcliffe** [comment]
@vsonnier this looks great! I'm going to make sure the new font path works with all the bundles on for each platform and then I'll merge this in.

**Comment by vsonnier** [comment]
@cjcliffe  I pushed an a fix for Spectrum where frequencies steps were not properly recomputed w.r.t real font size, and also a fix to lower mhz labels w.r.t font size, so that the spectrum ticks remains visible.

**Comment by vsonnier** [comment]
I've never noticed before now that the ticks marking integer values were thicker ! That was attention to detail :)

**Comment by cjcliffe** [comment]
@vsonnier lol, yeah that's pretty early code too -- I'm a fan of subtle visual hints :)

**Comment by cjcliffe** [comment]
@vsonnier the one I'm actually surprised nobody has caught to date is the fact that the Tuning Bar uses the Reddit up-vote / down-vote colors for tuning digits ;)

**Comment by cjcliffe** [comment]
Looks good on OSX and Linux; merged to master with a few tweaks

**Pull request merged**
